# src/config/training.yaml

# Nombre d'époques d'entraînement
epochs: 25

# Taille du batch (nombre d'images traitées par itération)
batch_size: 32

# Taux d'apprentissage
lr: 0.0001

# Optimiseur (actuellement supporté : adam, sgd)
optimizer: "adam"

# Scheduler de learning rate (facultatif)
scheduler: "cosine"

# Appareil : "cuda" pour GPU, "cpu" sinon
device: "cuda"

# Taille d'image standard
image_size: 96
